#!/usr/bin/env python3
"""Clean generated artifacts from the porting workflow."""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


def _remove_path(path: Path) -> bool:
    if not path.exists():
        return False
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()
    return True

def _remove_pycache(root: Path) -> list[str]:
    removed: list[str] = []
    if not root.exists():
        return removed
    for pycache_dir in root.rglob("__pycache__"):
        try:
            shutil.rmtree(pycache_dir)
            removed.append(str(pycache_dir))
        except OSError:
            continue
    return removed

def _remove_pytest_cache(root: Path) -> list[str]:
    removed: list[str] = []
    if not root.exists():
        return removed
    for pytest_cache_dir in root.rglob(".pytest_cache"):
        try:
            shutil.rmtree(pytest_cache_dir)
            removed.append(str(pytest_cache_dir))
        except OSError:
            continue
    return removed

def _remove_autogenerated_py(root: Path) -> list[str]:
    removed: list[str] = []
    if not root.exists():
        return removed
    for py_file in root.rglob("*.py"):
        m_file = py_file.with_suffix(".m")
        if not m_file.exists():
            continue
        try:
            content = py_file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "Auto-generated from MATLAB source" in content or "Fallback stub generated" in content:
            py_file.unlink(missing_ok=True)
            removed.append(str(py_file))
    return removed


def main() -> int:
    parser = argparse.ArgumentParser(description="Clean porting generated artifacts.")
    parser.add_argument("--clean-state", action="store_true", help="Remove state JSON.")
    parser.add_argument("--clean-reports", action="store_true", help="Remove report files.")
    parser.add_argument("--clean-tests", action="store_true", help="Remove generated tests folder.")
    parser.add_argument("--clean-temp-output", action="store_true", help="Remove old temporary generated python folder.")
    parser.add_argument("--clean-pycache", action="store_true", help="Remove pycache folders.")
    parser.add_argument("--clean-pytest-cache", action="store_true", help="Remove pytest cache folders.")
    parser.add_argument(
        "--clean-misaligned-generated",
        action="store_true",
        help="Remove auto-generated .py files accidentally written under monalisa/src.",
    )
    parser.add_argument("--all", action="store_true", help="Clean everything above.")
    args = parser.parse_args()

    base = Path(__file__).resolve().parent
    src_root = _project_root() / "src"
    removed: list[str] = []

    clean_state = args.clean_state or args.all
    clean_reports = args.clean_reports or args.all
    clean_tests = args.clean_tests or args.all
    clean_temp = args.clean_temp_output or args.all
    clean_misaligned = args.clean_misaligned_generated or args.all
    clean_pycache = args.clean_pycache or args.all
    clean_pytest_cache = args.clean_pytest_cache or args.all

    if clean_state:
        p = (base / "../state/porting_state.json").resolve()
        if _remove_path(p):
            removed.append(str(p))

    if clean_reports:
        p = (base / "../reports").resolve()
        if _remove_path(p):
            removed.append(str(p))

    if clean_tests:
        p = (base / "../tests/generated").resolve()
        if _remove_path(p):
            removed.append(str(p))

    if clean_temp:
        p = (base / "../python/monalisa_py/ported").resolve()
        if _remove_path(p):
            removed.append(str(p))

    if clean_misaligned:
        wrong_root = src_root.resolve()
        removed.extend(_remove_autogenerated_py(wrong_root))
        removed.extend(_remove_pycache(wrong_root))
        removed.extend(_remove_pytest_cache(wrong_root))

    if clean_pycache:
        removed.extend(_remove_pycache(src_root))

    if clean_pytest_cache:
        removed.extend(_remove_pytest_cache(src_root))

    print(f"Removed {len(removed)} path(s).")
    for item in removed:
        print(f"- {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
