#!/usr/bin/env python3
"""Generate MATLAB-native compatibility helpers for translated Python code.

This script builds/updates:
  third_part/matlab_compat/matlab_native.py

It extracts probable MATLAB native function names from TODO(matlab-*) markers
and creates deterministic lightweight wrappers so auto_fix_missing_imports can
import them when unresolved calls are detected.
"""
from __future__ import annotations

import argparse
import ast
import builtins
import json
import keyword
import re
from pathlib import Path


MATLAB_TODO_RE = re.compile(r"TODO\(matlab-[^)]+\):\s*(.*)")
CALL_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")
VALID_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

MATLAB_KEYWORDS = {
    "if",
    "for",
    "while",
    "switch",
    "case",
    "otherwise",
    "end",
    "try",
    "catch",
    "function",
    "classdef",
}

# Curated compatibility set for common MATLAB native helpers in translated files.
SEED_FUNCTIONS = {
    "addpath",
    "genpath",
    "fullfile",
    "str2double",
    "num2str",
    "length",
    "isempty",
    "size",
    "nnz",
    "logical",
    "double",
    "single",
    "padarray",
    "roipoly",
    "movstd",
    "repmat",
    "permute",
    "questdlg",
    "inputdlg",
    "disp",
    "clear",
    "save",
    "load",
    "figure",
    "hold",
    "imagesc",
    "colorbar",
    "colormap",
    "plot",
    "scatter",
    "xlabel",
    "ylabel",
    "title",
    "legend",
    "grid",
    "xlim",
    "ylim",
    "xline",
    "text",
    "gca",
    "gcf",
    "set",
    "uicontrol",
}


MODULE_HEADER = '''"""Auto-generated MATLAB native compatibility helpers.

This module is generated by:
  porting/scripts/generate_matlab_native_compat.py
"""

from __future__ import annotations

import os
import math
from pathlib import Path

import numpy as np

try:
    import scipy.io as _scipy_io
except Exception:  # noqa: BLE001
    _scipy_io = None


def addpath(*_args, **_kwargs):
    return None


def genpath(path):
    return str(path)


def fullfile(*parts):
    cleaned = [str(p) for p in parts if p is not None and str(p) != ""]
    if not cleaned:
        return ""
    return os.path.join(*cleaned)


def str2double(value):
    try:
        return float(value)
    except Exception:  # noqa: BLE001
        return float("nan")


def num2str(value):
    return str(value)


def length(value):
    arr = np.asarray(value)
    if arr.ndim == 0:
        return 1
    return int(max(arr.shape))


def isempty(value):
    if value is None:
        return True
    try:
        return len(value) == 0
    except Exception:  # noqa: BLE001
        arr = np.asarray(value)
        return arr.size == 0


def size(value, dim=None):
    shape = np.asarray(value).shape
    if dim is None:
        return tuple(shape)
    idx = int(dim) - 1
    if idx < 0 or idx >= len(shape):
        return 1
    return int(shape[idx])


def nnz(value):
    return int(np.count_nonzero(value))


def logical(value):
    return np.asarray(value, dtype=bool)


def double(value):
    return np.asarray(value, dtype=np.float64)


def single(value):
    return np.asarray(value, dtype=np.float32)


def repmat(value, reps):
    return np.tile(value, reps)


def permute(value, order):
    order = [int(i) - 1 if int(i) >= 1 else int(i) for i in order]
    return np.transpose(value, axes=order)


def movstd(values, window):
    arr = np.asarray(values, dtype=float)
    w = max(int(window), 1)
    if arr.ndim != 1:
        arr = arr.reshape(-1)
    out = np.zeros_like(arr, dtype=float)
    for i in range(arr.size):
        lo = max(0, i - w // 2)
        hi = min(arr.size, i + (w - w // 2))
        out[i] = float(np.std(arr[lo:hi]))
    return out


def padarray(arr, pad_width, value=0, direction="both"):
    a = np.asarray(arr)
    if isinstance(pad_width, int):
        pads = [(pad_width, pad_width)] * a.ndim
    else:
        pw = list(pad_width)
        if pw and not isinstance(pw[0], (list, tuple)):
            pads = [(int(p), int(p)) for p in pw] + [(0, 0)] * max(0, a.ndim - len(pw))
        else:
            pads = [(int(p[0]), int(p[1])) for p in pw] + [(0, 0)] * max(0, a.ndim - len(pw))
        pads = pads[: a.ndim]
    if direction == "pre":
        pads = [(p[0], 0) for p in pads]
    elif direction == "post":
        pads = [(0, p[1]) for p in pads]
    return np.pad(a, pads, mode="constant", constant_values=value)


def roipoly(*args, **kwargs):
    # Minimal compatible implementation:
    # roipoly(image_shape, x_vertices, y_vertices) -> bool mask
    if len(args) >= 3:
        first = np.asarray(args[0])
        if first.ndim >= 2:
            shape = first.shape[:2]
        else:
            shape = tuple(int(v) for v in first[:2])
        xv = np.asarray(args[1], dtype=float).reshape(-1)
        yv = np.asarray(args[2], dtype=float).reshape(-1)
    else:
        shape = kwargs.get("shape", (0, 0))
        xv = np.asarray(kwargs.get("xv", []), dtype=float).reshape(-1)
        yv = np.asarray(kwargs.get("yv", []), dtype=float).reshape(-1)

    if len(shape) < 2 or xv.size == 0 or yv.size == 0:
        return np.zeros((int(shape[0]) if shape else 0, int(shape[1]) if len(shape) > 1 else 0), dtype=bool)

    h, w = int(shape[0]), int(shape[1])
    try:
        from matplotlib.path import Path as _MplPath  # lazy import

        yy, xx = np.mgrid[0:h, 0:w]
        pts = np.vstack((xx.ravel(), yy.ravel())).T
        poly = np.vstack((xv, yv)).T
        mask = _MplPath(poly).contains_points(pts)
        return mask.reshape((h, w))
    except Exception:  # noqa: BLE001
        # Cheap fallback: bounding box mask.
        x0, x1 = int(np.floor(np.min(xv))), int(np.ceil(np.max(xv)))
        y0, y1 = int(np.floor(np.min(yv))), int(np.ceil(np.max(yv)))
        mask = np.zeros((h, w), dtype=bool)
        x0 = max(0, x0)
        y0 = max(0, y0)
        x1 = min(w - 1, x1)
        y1 = min(h - 1, y1)
        if x1 >= x0 and y1 >= y0:
            mask[y0 : y1 + 1, x0 : x1 + 1] = True
        return mask


def questdlg(_message, _title="Confirm", yes="Yes", _no="No", _default="Yes"):
    return yes


def inputdlg(_message, _title="Input", _shape=None, defaults=None):
    if defaults and len(defaults) > 0:
        return [str(defaults[0])]
    return ["0"]


def disp(value):
    print(value)
    return None


def clear(*_args, **_kwargs):
    return None


def save(path, *args):
    if _scipy_io is None:
        np.savez(str(path), *args)
        return None
    payload = {}
    if len(args) % 2 == 0 and all(isinstance(args[i], str) for i in range(0, len(args), 2)):
        for i in range(0, len(args), 2):
            payload[str(args[i])] = np.asarray(args[i + 1])
    else:
        for idx, val in enumerate(args):
            payload[f"var_{idx}"] = np.asarray(val)
    _scipy_io.savemat(str(path), payload)
    return None


def load(path):
    p = Path(path)
    if _scipy_io is not None and p.suffix.lower() == ".mat":
        return _scipy_io.loadmat(str(p))
    if p.exists():
        try:
            data = np.load(str(p), allow_pickle=True)
            return {k: data[k] for k in data.files}
        except Exception:  # noqa: BLE001
            return {}
    return {}


def figure(*_args, **_kwargs):
    return None


def hold(*_args, **_kwargs):
    return None


def imagesc(*_args, **_kwargs):
    return None


def colorbar(*_args, **_kwargs):
    return None


def colormap(*_args, **_kwargs):
    return None


def plot(*_args, **_kwargs):
    return None


def scatter(*_args, **_kwargs):
    return None


def xlabel(*_args, **_kwargs):
    return None


def ylabel(*_args, **_kwargs):
    return None


def title(*_args, **_kwargs):
    return None


def legend(*_args, **_kwargs):
    return None


def grid(*_args, **_kwargs):
    return None


def xlim(*_args, **_kwargs):
    return None


def ylim(*_args, **_kwargs):
    return None


def xline(*_args, **_kwargs):
    return None


def text(*_args, **_kwargs):
    return None


def gca():
    return None


def gcf():
    return None


def set(*_args, **_kwargs):
    return None


def uicontrol(*_args, **_kwargs):
    return None
'''


def _iter_files(roots: list[Path], pattern: str) -> list[Path]:
    out: list[Path] = []
    for root in roots:
        if root.exists():
            out.extend([p for p in root.rglob(pattern) if p.is_file()])
    dedup = {p.resolve(): p for p in out}
    return sorted(dedup.values(), key=lambda p: str(p))


def _defined_symbols(py_files: list[Path]) -> set[str]:
    symbols: set[str] = set()
    for path in py_files:
        try:
            tree = ast.parse(path.read_text(encoding="utf-8", errors="ignore"))
        except SyntaxError:
            continue
        for node in getattr(tree, "body", []):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                symbols.add(node.name)
    return symbols


def _extract_candidates_from_python_todos(py_files: list[Path]) -> set[str]:
    names: set[str] = set()
    for path in py_files:
        text = path.read_text(encoding="utf-8", errors="ignore")
        for line in text.splitlines():
            m = MATLAB_TODO_RE.search(line)
            if not m:
                continue
            payload = m.group(1)
            for call in CALL_RE.findall(payload):
                names.add(call)
    return names


def _is_valid_name(name: str) -> bool:
    if not VALID_IDENT_RE.match(name):
        return False
    if keyword.iskeyword(name):
        return False
    if name.lower() in MATLAB_KEYWORDS:
        return False
    if name in dir(builtins):
        return False
    return True


def _is_plausible_matlab_native_name(name: str) -> bool:
    if name in SEED_FUNCTIONS:
        return True
    # Keep only simple lowercase native-like names beyond curated seed set.
    if any(ch.isupper() for ch in name):
        return False
    if "_" in name:
        return False
    project_prefixes = ("bm", "bca", "mle", "dh", "ml", "test", "run")
    if any(name.startswith(prefix) for prefix in project_prefixes):
        return False
    return True


def _generic_wrapper(name: str) -> str:
    return f'''
def {name}(*args, **kwargs):
    fn = getattr(np, "{name}", None)
    if callable(fn):
        try:
            return fn(*args, **kwargs)
        except Exception:  # noqa: BLE001
            pass
    return None
'''.strip(
        "\n"
    )


def _build_module_text(extra_names: list[str]) -> str:
    chunks = [MODULE_HEADER.rstrip()]
    for name in extra_names:
        if name in SEED_FUNCTIONS:
            continue
        chunks.append("")
        chunks.append(_generic_wrapper(name))
    chunks.append("")
    chunks.append("__all__ = [name for name in globals() if not name.startswith('_')]")
    chunks.append("")
    return "\n".join(chunks)


def generate_native_compat(roots: list[Path], repo_root: Path, apply: bool, include_discovered: bool) -> dict:
    py_files = _iter_files(roots, "*.py")
    defined = _defined_symbols(py_files)
    todo_candidates = _extract_candidates_from_python_todos(py_files)

    merged = set(SEED_FUNCTIONS)
    if include_discovered:
        merged.update(todo_candidates)
    merged = {name for name in merged if _is_valid_name(name)}
    merged = {name for name in merged if _is_plausible_matlab_native_name(name)}
    missing = sorted(name for name in merged if name not in defined)

    compat_dir = repo_root / "third_part" / "matlab_compat"
    compat_file = compat_dir / "matlab_native.py"
    init_root = repo_root / "third_part" / "__init__.py"
    init_compat = compat_dir / "__init__.py"

    module_text = _build_module_text(missing)
    old_text = compat_file.read_text(encoding="utf-8", errors="ignore") if compat_file.exists() else ""
    changed = old_text != module_text

    if apply:
        compat_dir.mkdir(parents=True, exist_ok=True)
        if not init_root.exists():
            init_root.write_text("", encoding="utf-8")
        if not init_compat.exists():
            init_compat.write_text("", encoding="utf-8")
        compat_file.write_text(module_text, encoding="utf-8")

    return {
        "mode": "apply" if apply else "dry-run",
        "roots": [str(p) for p in roots],
        "python_files_scanned": len(py_files),
        "todo_candidate_functions": len(todo_candidates),
        "include_discovered": include_discovered,
        "compat_functions_generated": len(missing),
        "compat_file": str(compat_file),
        "compat_changed": changed,
        "generated_function_names": missing,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate MATLAB native compatibility helpers.")
    parser.add_argument(
        "--roots",
        default="src,demo,tests,third_part",
        help="Comma-separated roots to scan for TODO(matlab-*) markers.",
    )
    parser.add_argument("--repo-root", default="../../", help="Repository root.")
    parser.add_argument("--apply", action="store_true", help="Apply changes (default dry-run).")
    parser.add_argument(
        "--include-discovered",
        action="store_true",
        help="Also generate wrappers for discovered TODO(matlab-*) function names.",
    )
    parser.add_argument("--output", default="../reports/matlab_native_compat_report.json", help="Output report path.")
    parser.add_argument("--summary-only", action="store_true", help="Print compact summary.")
    args = parser.parse_args()

    base = Path(__file__).resolve().parent
    repo_root = (base / args.repo_root).resolve()
    roots = [(repo_root / token.strip()).resolve() for token in args.roots.split(",") if token.strip()]

    report = generate_native_compat(
        roots=roots,
        repo_root=repo_root,
        apply=args.apply,
        include_discovered=args.include_discovered,
    )
    output = (base / args.output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2), encoding="utf-8")

    if args.summary_only:
        compact = {
            "mode": report["mode"],
            "python_files_scanned": report["python_files_scanned"],
            "todo_candidate_functions": report["todo_candidate_functions"],
            "compat_functions_generated": report["compat_functions_generated"],
            "compat_changed": report["compat_changed"],
        }
        print(json.dumps(compact, indent=2))
    else:
        print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
