"""
Python translation of the MATLAB function
    bmArray2Binary_sparseMat(s, argDir)

The original autogenerated translation was heavily incomplete
and contained MATLAB-specific calls (`mkdir`, `dlmwrite`, `error`,
etc.) that do not exist in Python.  The implementation below
provides a straightforward, pure-Python replacement that
conforms to the MATLAB behaviour:

* Raises a ValueError if the sparse matrix type is `'void'`.
* Creates the output directory (`argDir`) if it does not exist.
* Writes the header file ``bmArray2Binary_sparseMat_header.txt``
  with the same fields that the MATLAB version writes.
* Calls :func:`bmArray2Binary` (imported from the third-party
  implementation) to write the binary data for the supported
  sparseMat types.
"""

import os

# The binary writer is a third-party implementation.
from src.readWrite.bmArray2Binary import bmArray2Binary


def _write_header(my_file, lines):
    """
    Helper to write the header file, one entry per line.
    The MATLAB code uses ``dlmwrite`` with empty delimiter and
    ``newline='pc'``.  For our purposes plain text with a newline
    is sufficient and cross-platform.
    """
    with open(my_file, "w", newline="\n") as f:
        for line in lines:
            f.write(f"{line}\n")


def bmArray2Binary_sparseMat(s, argDir):
    """
    Write a ``sparseMat`` structure ``s`` to binary files inside
    ``argDir``.  The behaviour matches the MATLAB reference.

    Parameters
    ----------
    s : object
        The sparse matrix descriptor.  It must provide the
        attributes used in the MATLAB code (``type``,
        ``block_type``, ``kernel_type``, ``r_size``, ``l_size``,
        ``l_nJump``, ``nBlock`` and the data fields that depend
        on the type).
    argDir : str
        Target directory in which the binary files and the header
        text file are created.

    Raises
    ------
    ValueError
        If ``s.type`` is ``'void'`` or if an unsupported sparseMat
        type is encountered.
    """
    # Handle the 'void' case (MATLAB error + return)
    if s.type == "void":
        raise ValueError("The sparseMat object is of type 'void'.")

    # Ensure output directory exists
    os.makedirs(argDir, exist_ok=True)

    # Build header file path
    my_file = os.path.join(argDir, "bmArray2Binary_sparseMat_header.txt")

    # Extract fields used in the header
    type_string = s.type
    block_type_string = s.block_type
    kernel_type_string = s.kernel_type
    r_size_string = str(s.r_size)
    l_size_string = str(s.l_size)
    l_nJump_string = str(s.l_nJump)
    nBlock_string = str(s.nBlock)

    # ------------------------------------------------------------------
    # MATLAB:  if strcmp(s.type, 'matlab_ind') || strcmp(s.type, 'l_squeezed_matlab_ind')
    # ------------------------------------------------------------------
    if s.type in ("matlab_ind", "l_squeezed_matlab_ind"):
        bmArray2Binary(s.r_nJump, argDir, "r_nJump", "int")
        bmArray2Binary(s.r_ind, argDir, "r_ind", "int")
        bmArray2Binary(s.m_val, argDir, "m_val", "single")
        bmArray2Binary(s.l_ind, argDir, "l_ind", "int")
        bmArray2Binary(s.N_u, argDir, "N_u", "int")
        bmArray2Binary(s.d_u, argDir, "d_u", "single")
        bmArray2Binary(s.nWin, argDir, "nWin", "int")
        bmArray2Binary(s.kernelParam, argDir, "kernelParam", "single")

        header_lines = [
            type_string,
            block_type_string,
            kernel_type_string,
            r_size_string,
            l_size_string,
            l_nJump_string,
        ]
        _write_header(my_file, header_lines)

    # ------------------------------------------------------------------
    # MATLAB:  elseif strcmp(s.type, 'cpp_prepared') || strcmp(s.type, 'l_squeezed_cpp_prepared')
    # ------------------------------------------------------------------
    elif s.type in ("cpp_prepared", "l_squeezed_cpp_prepared"):
        bmArray2Binary(s.r_nJump, argDir, "r_nJump", "int")
        bmArray2Binary(s.r_jump, argDir, "r_jump", "int")
        bmArray2Binary(s.m_val, argDir, "m_val", "single")
        bmArray2Binary(s.l_jump, argDir, "l_jump", "int")
        bmArray2Binary(s.N_u, argDir, "N_u", "int")
        bmArray2Binary(s.d_u, argDir, "d_u", "single")
        bmArray2Binary(s.nWin, argDir, "nWin", "int")
        bmArray2Binary(s.kernelParam, argDir, "kernelParam", "single")
        bmArray2Binary(s.block_length, argDir, "block_length", "int")
        bmArray2Binary(s.l_block_start, argDir, "l_block_start", "int")
        bmArray2Binary(s.m_block_start, argDir, "m_block_start", "int64")

        header_lines = [
            type_string,
            block_type_string,
            kernel_type_string,
            r_size_string,
            l_size_string,
            l_nJump_string,
            nBlock_string,
        ]
        _write_header(my_file, header_lines)

    else:
        raise ValueError(f"Unsupported sparseMat type: {s.type}")

    # No explicit return value - the MATLAB function returns nothing
    return
