"""Auto-generated MATLAB native compatibility helpers.

This module is generated by:
  porting/scripts/generate_matlab_native_compat.py
"""

from __future__ import annotations

import os
import math
from pathlib import Path

import numpy as np

try:
    import scipy.io as _scipy_io
except Exception:  # noqa: BLE001
    _scipy_io = None


def addpath(*_args, **_kwargs):
    return None


def genpath(path):
    return str(path)


def fullfile(*parts):
    cleaned = [str(p) for p in parts if p is not None and str(p) != ""]
    if not cleaned:
        return ""
    return os.path.join(*cleaned)


def str2double(value):
    try:
        return float(value)
    except Exception:  # noqa: BLE001
        return float("nan")


def num2str(value):
    return str(value)


def length(value):
    arr = np.asarray(value)
    if arr.ndim == 0:
        return 1
    return int(max(arr.shape))


def isempty(value):
    if value is None:
        return True
    try:
        return len(value) == 0
    except Exception:  # noqa: BLE001
        arr = np.asarray(value)
        return arr.size == 0


def size(value, dim=None):
    shape = np.asarray(value).shape
    if dim is None:
        return tuple(shape)
    idx = int(dim) - 1
    if idx < 0 or idx >= len(shape):
        return 1
    return int(shape[idx])


def nnz(value):
    return int(np.count_nonzero(value))


def logical(value):
    return np.asarray(value, dtype=bool)


def double(value):
    return np.asarray(value, dtype=np.float64)


def single(value):
    return np.asarray(value, dtype=np.float32)


def repmat(value, reps):
    return np.tile(value, reps)


def permute(value, order):
    order = [int(i) - 1 if int(i) >= 1 else int(i) for i in order]
    return np.transpose(value, axes=order)


def movstd(values, window):
    arr = np.asarray(values, dtype=float)
    w = max(int(window), 1)
    if arr.ndim != 1:
        arr = arr.reshape(-1)
    out = np.zeros_like(arr, dtype=float)
    for i in range(arr.size):
        lo = max(0, i - w // 2)
        hi = min(arr.size, i + (w - w // 2))
        out[i] = float(np.std(arr[lo:hi]))
    return out


def padarray(arr, pad_width, value=0, direction="both"):
    a = np.asarray(arr)
    if isinstance(pad_width, int):
        pads = [(pad_width, pad_width)] * a.ndim
    else:
        pw = list(pad_width)
        if pw and not isinstance(pw[0], (list, tuple)):
            pads = [(int(p), int(p)) for p in pw] + [(0, 0)] * max(0, a.ndim - len(pw))
        else:
            pads = [(int(p[0]), int(p[1])) for p in pw] + [(0, 0)] * max(0, a.ndim - len(pw))
        pads = pads[: a.ndim]
    if direction == "pre":
        pads = [(p[0], 0) for p in pads]
    elif direction == "post":
        pads = [(0, p[1]) for p in pads]
    return np.pad(a, pads, mode="constant", constant_values=value)


def roipoly(*args, **kwargs):
    # Minimal compatible implementation:
    # roipoly(image_shape, x_vertices, y_vertices) -> bool mask
    if len(args) >= 3:
        first = np.asarray(args[0])
        if first.ndim >= 2:
            shape = first.shape[:2]
        else:
            shape = tuple(int(v) for v in first[:2])
        xv = np.asarray(args[1], dtype=float).reshape(-1)
        yv = np.asarray(args[2], dtype=float).reshape(-1)
    else:
        shape = kwargs.get("shape", (0, 0))
        xv = np.asarray(kwargs.get("xv", []), dtype=float).reshape(-1)
        yv = np.asarray(kwargs.get("yv", []), dtype=float).reshape(-1)

    if len(shape) < 2 or xv.size == 0 or yv.size == 0:
        return np.zeros((int(shape[0]) if shape else 0, int(shape[1]) if len(shape) > 1 else 0), dtype=bool)

    h, w = int(shape[0]), int(shape[1])
    try:
        from matplotlib.path import Path as _MplPath  # lazy import

        yy, xx = np.mgrid[0:h, 0:w]
        pts = np.vstack((xx.ravel(), yy.ravel())).T
        poly = np.vstack((xv, yv)).T
        mask = _MplPath(poly).contains_points(pts)
        return mask.reshape((h, w))
    except Exception:  # noqa: BLE001
        # Cheap fallback: bounding box mask.
        x0, x1 = int(np.floor(np.min(xv))), int(np.ceil(np.max(xv)))
        y0, y1 = int(np.floor(np.min(yv))), int(np.ceil(np.max(yv)))
        mask = np.zeros((h, w), dtype=bool)
        x0 = max(0, x0)
        y0 = max(0, y0)
        x1 = min(w - 1, x1)
        y1 = min(h - 1, y1)
        if x1 >= x0 and y1 >= y0:
            mask[y0 : y1 + 1, x0 : x1 + 1] = True
        return mask


def questdlg(_message, _title="Confirm", yes="Yes", _no="No", _default="Yes"):
    return yes


def inputdlg(_message, _title="Input", _shape=None, defaults=None):
    if defaults and len(defaults) > 0:
        return [str(defaults[0])]
    return ["0"]


def disp(value):
    print(value)
    return None


def clear(*_args, **_kwargs):
    return None


def save(path, *args):
    if _scipy_io is None:
        np.savez(str(path), *args)
        return None
    payload = {}
    if len(args) % 2 == 0 and all(isinstance(args[i], str) for i in range(0, len(args), 2)):
        for i in range(0, len(args), 2):
            payload[str(args[i])] = np.asarray(args[i + 1])
    else:
        for idx, val in enumerate(args):
            payload[f"var_{idx}"] = np.asarray(val)
    _scipy_io.savemat(str(path), payload)
    return None


def load(path):
    p = Path(path)
    if _scipy_io is not None and p.suffix.lower() == ".mat":
        return _scipy_io.loadmat(str(p))
    if p.exists():
        try:
            data = np.load(str(p), allow_pickle=True)
            return {k: data[k] for k in data.files}
        except Exception:  # noqa: BLE001
            return {}
    return {}


def figure(*_args, **_kwargs):
    return None


def hold(*_args, **_kwargs):
    return None


def imagesc(*_args, **_kwargs):
    return None


def colorbar(*_args, **_kwargs):
    return None


def colormap(*_args, **_kwargs):
    return None


def plot(*_args, **_kwargs):
    return None


def scatter(*_args, **_kwargs):
    return None


def xlabel(*_args, **_kwargs):
    return None


def ylabel(*_args, **_kwargs):
    return None


def title(*_args, **_kwargs):
    return None


def legend(*_args, **_kwargs):
    return None


def grid(*_args, **_kwargs):
    return None


def xlim(*_args, **_kwargs):
    return None


def ylim(*_args, **_kwargs):
    return None


def xline(*_args, **_kwargs):
    return None


def text(*_args, **_kwargs):
    return None


def gca():
    return None


def gcf():
    return None


def set(*_args, **_kwargs):
    return None


def uicontrol(*_args, **_kwargs):
    return None

__all__ = [name for name in globals() if not name.startswith('_')]
