# During a push on the main branch, the code is tested and the file describing the results of the matlab code is written
# the tests are performed in docker containers with example data. The results of these tests are then published on the project's github page
# The workflow is triggered by a push on the main branch. It uses the sphinx-notes/pages action to build the Sphinx documentation from the RST files located in the ./docs/rst directory, installing the dependencies listed in ./docs/requirements.txt. The result of the build is then published on GitHub Pages using the peaceiris/actions-gh-pages action.



name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-22.04
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/rst
        requirements_path: ./docs/requirements.txt
        publish: false
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
